name: rmw
description: A simple command-line application.
version: 0.0.1
homepage: https://rmw.link

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies: 
  objectbox: ^1.2.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.0
  objectbox_generator: any
  build_version: ^2.1.0
