name: rmw
description: A simple command-line application.
version: 0.0.1
homepage: https://rmw.link

environment:
  sdk: '>=2.15.0-178.1.beta <3.0.0'

dependencies: 
  objectbox: ^1.2.0
  on_exit: ^1.0.0
  path: ^1.8.0
  rmwlog: ^1.0.10
  settings_yaml: ^3.0.6
  try_catch: ^1.0.2
  upnp_port_forward: ^1.0.8

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.0
  objectbox_generator: any
  build_version: ^2.1.0
