name: rmw
description: A simple command-line application.
version: 0.0.1
homepage: https://rmw.link

environment:
  sdk: '>=2.15.0-1.1.beta <3.0.0'

dependencies: 
  intranet_ip: ^1.0.2
  objectbox: ^1.2.0
  path: ^1.8.0
  upnp_port_forward: ^1.0.5

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.0
  objectbox_generator: any
  build_version: ^2.1.0
